# Generated by Django 5.1.1 on 2024-09-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewards',
            old_name='price',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='stock',
        ),
    ]
