# Generated by Django 5.1.1 on 2024-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rename_price_rewards_points_remove_rewards_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='points',
            field=models.IntegerField(),
        ),
    ]
