# Generated by Django 5.1.1 on 2024-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_menutest_menu_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_url',
            field=models.CharField(max_length=2550),
        ),
    ]
